### ISSUE TITLE
No way to access alertmanager

### ISSUE THREAD

**Issue by bhudlemeyer** [pivotal-cf/pcf-prometheus-pipeline#12]
The current pipeline makes it so you can not access alert manager. Didn't notice it was missing from the port list at the bottom at first went looking and saw the password is not set it would appear. 

simply adding below to pipeline.yml and params file allows access to alertsmanager

Pipeline.yml file add to the deploy vars section:

        alertmanager_password: ((alertmanager_password))

Params file add: 

    alertmanager_password: PASSWORD

If desired will submit pull request for this and other var issue I found under ticket https://github.com/pivotal-cf/pcf-prometheus-pipeline/issues/11

**Comment by mkuratczyk** [comment]
Similar to #11 - this seems to be caused by not using Credhub as a BOSH config server. In this case however, the operator has a reason to know the password so I added this to params.yml. Thank you!
