### ISSUE TITLE
External BOSH Director config is ignored when creating UAA clients

### ISSUE THREAD

**Issue by henryaj** [pivotal-cf/pcf-prometheus-pipeline#13]
The code at https://github.com/pivotal-cf/pcf-prometheus-pipeline/blob/b390ca00065bda363e48f64e5f9524dcf6cfc815/pipeline/tasks/common.sh#L39-L41 always gets the director IP and creds from OpsMan, even if an external director has been specified.

We ran into this when we tried attaching a public-facing IP address to our OpsMan director in an attempt to reach it from our Concourse instance (which is outside the OpsMan private network).

The failure we see in `create-uaa-clients` is:

> Logging into BOSH UAA...
> failed to access https://10.0.0.5:8443: execution expired

Thanks!

Henry && @jamesjoshuahill

**Comment by mkuratczyk** [comment]
This is the expected (and I believe correct) behaviour. The goal of this task is to create UAA clients for Prometheus exporters. Even if you are deploying Prometheus to an external BOSH director, you want your bosh_exporter to monitor the PCF BOSH Director (OpsMan Director). Unless you disagree I'll close this issue in favour of https://github.com/pivotal-cf/pcf-prometheus-pipeline/issues/14.

**Comment by henryaj** [comment]
Yep, that makes sense.
