### ISSUE TITLE
external_bosh.sh

### ISSUE THREAD

**Issue by manaspatkar21** [pivotal-cf/pcf-prometheus-pipeline#17]
Hello,
        I looked at the github page for mkuratczyk/bosh-creds-resource, I see that for "external_bosh", a file called "external_bosh.json" is generated. However in the code for common.sh, it looks for "external_bosh.sh" file. How is this shell script generated ?

**Comment by mkuratczyk** [comment]
Hi. Thanks, I'll need to look into that. I had an accidental commit in the bosh-creds-resource repo which I reverted and I probably reverted more than I wanted. I remember I wanted to have the same data as .sh for easy sourcing of the creds.

**Comment by mkuratczyk** [comment]
Should be fixed in https://github.com/pivotal-cf/pcf-prometheus-pipeline/commit/fa004e6901853d1ccc080b45f549a6afbcb734a9.

This file is now generated again: https://github.com/pivotalservices/bosh-creds-resource/commit/92583d438cbdbde56a6d6ab58a61d61510b69aa8
