### ISSUE TITLE
how to add custom alerts in prometheus ?

### ISSUE THREAD

**Issue by manaspatkar21** [pivotal-cf/pcf-prometheus-pipeline#19]

**Comment by mkuratczyk** [comment]
This pipeline has been designed to easily get started, not necessarily to support more sophisticated deployments. Therefore there is no built-in feature to add custom alerts.

The best way to achieve that would be to build a simple bosh release which only includes your custom alert files and colocate this bosh release with your other alerts. This will require changes to pipeline.yml.

**Comment by mkuratczyk** [comment]
Right, I forgot about this option (additional bosh release is probably still the way to go if you want custom dashboards and share them between multiple deployments). Prometheus alert format changed between Prometheus 1 and 2 so you need to use the syntax for the right version. Compare for example:
https://github.com/bosh-prometheus/prometheus-boshrelease/blob/v21.1.1/jobs/bosh_alerts/templates/bosh_jobs.alerts (v1 syntax)
and https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/bosh_alerts/templates/bosh_jobs.alerts.yml (v2 YAML syntax).

To add such custom alerts to the pipeline you could create an ops file like this: https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/bosh_alerts/templates/bosh_jobs.alerts.yml and add this ops file to the list in pipeline.yml (https://github.com/pivotal-cf/pcf-prometheus-pipeline/blob/master/pipeline/pipeline.yml#L96).

**Comment by mkuratczyk** [comment]
Seems like it's been resolved at https://github.com/bosh-prometheus/prometheus-boshrelease/issues/211
