### ISSUE TITLE
NGINX SSL PROTOCOL ERROR for https

### ISSUE THREAD

**Issue by stephendotsaenzataigdotcom** [pivotal-cf/pcf-prometheus-pipeline#23]
I deployed the pipeline and it ran successfully.  I am able to hit NGINX on all 3 indicated ports (3000,9090,9093) via http.  But when I try using https, I get an error indicating:

(Chrome): ERR_SSL_PROTOCOL_ERROR
(Firefox): An error occurred during a connection to 10.15.228.105:3000. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

Google searches haven't resulted in anything helpful, so any direction would be appreciated.

**Comment by mkuratczyk** [comment]
Sorry, completely missed this issues. If you can connect using HTTP then you can't connect using HTTPS on the same port. This pipeline currently doesn't set up HTTPs, you'd have to modify it.
