### ISSUE TITLE
firehose_exporter and cf_exporter not scraped when using external_bosh

### ISSUE THREAD

**Issue by mkuratczyk** [pivotal-cf/pcf-prometheus-pipeline#5]
Currently if deploying to an external bosh director, cf_exporter and firehose_exporter are not scraped (not included in the target list). This is because Prometheus is configured for bosh-based service discovery but the VMs running these exporters are managed by a different bosh and therefore not found. cf_exporter has been fixed on the external_bosh branch. Fix for firehose_exporter is not yet available.

**Comment by johnlonganecker** [comment]
Any idea when the firehose_exporter will be fixed?

**Comment by mkuratczyk** [comment]
I'll be looking into this over the next few days.

**Comment by johnlonganecker** [comment]
should we change this https://github.com/pivotal-cf/pcf-prometheus-pipeline/blob/external_bosh/pipeline/pipeline.yml#L17

from `master` to `external_bosh`

**Comment by mkuratczyk** [comment]
Once I have firehose_exporter working I will merge that branch. Currently it only gives you cf_exporter so not much value without firehose_exporter.

**Comment by johnlonganecker** [comment]
👍  thanks!

**Comment by johnlonganecker** [comment]
Any update on this? Thanks!

**Comment by mkuratczyk** [comment]
I sent you a DM on OSS CF slack. Would you find a moment to discuss the options for solving this problem? Thanks,

**Comment by johnlonganecker** [comment]
Sounds good talk to you there.

**Comment by mkuratczyk** [comment]
Please try now.
