### ISSUE TITLE
delete-deployment does not work when using an external bosh

### ISSUE THREAD

**Issue by johnlonganecker** [pivotal-cf/pcf-prometheus-pipeline#6]
we can't delete the prometheus deployment with the pipeline. We are using an external bosh.

**Comment by mkuratczyk** [comment]
Fixed in [86e5d93](https://github.com/pivotal-cf/pcf-prometheus-pipeline/commit/86e5d930a5f826fc544fcbc9c6da42b6c23b1e8b).
