### ISSUE TITLE
commit 96bb739 breaks the pipeline, as tasks are still referencing old pcf-prometheus-git resource

### ISSUE THREAD

**Issue by acloudtechie** [pivotal-cf/pcf-prometheus-pipeline#7]
Take the latest build and the pipeline failed on the create-uaa-clients job: "unknown artifact source: pcf-prometheus-git."

Looks like the pipeline still references the old resource name for tasks, such as create-aaa-clients: "file: pcf-prometheus-git/pipeline/tasks/create-uaa-clients.yml"

**Comment by mkuratczyk** [comment]
Sorry for that. I can't go through the full test right now but hopefully it's fixed now. I'd appreciate if you could let me know if it work for you now. Otherwise I'll check next week.

**Comment by mkuratczyk** [comment]
Everything should work now.
