### ISSUE TITLE
Missing data for Grafana Dashboards when using "external_bosh"

### ISSUE THREAD

**Issue by acloudtechie** [pivotal-cf/pcf-prometheus-pipeline#9]
When using the external_bosh, many of the dashboards have no data, including APP, CF, and System dashboards.  Could be related to the Bosh Service Discovery.  When the prometheus stacks are installed outside of the PCF, exporters are not successfully discovered based on the  monitor-bosh.yml op file.

**Comment by mkuratczyk** [comment]
Yes, this is related to https://github.com/pivotal-cf/pcf-prometheus-pipeline/issues/5. I'm working on it as we speak and hopefully will push the fix within a few hours. The solution/workaround is that firehose_exporter will be running locally on Prometheus VM (cf_exporter is already there anyway) and they will be hardcoded as targets available on localhost.

**Comment by mkuratczyk** [comment]
Please try now.
